/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DevelopmentEnvironmentMetadata {
  /**
   * The development environment or platform used (e.g., 'Node.js v14.17.0').
   */
  environment: string;
  /**
   * A mapping of libraries or packages used, along with their versions.
   */
  libraries: {
    /**
     * Version of the library or package used.
     */
    [k: string]: string;
  };
  /**
   * The tool used for building or compiling the project (e.g., 'webpack v5.38.1').
   */
  buildTool?: string;
  /**
   * The Git commit hash corresponding to the codebase at the time of credential issuance.
   */
  commitHash?: string;
  /**
   * The date and time when the credential was generated.
   */
  timestamp: string;
  /**
   * The operating system used in the development environment (e.g., 'Ubuntu 20.04').
   */
  operatingSystem?: string;
  /**
   * The hostname of the machine running the development environment.
   */
  hostname?: string;
  /**
   * The IP address of the machine running the development environment.
   */
  ipAddress?: string;
  [k: string]: unknown;
}
