/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DevelopmentEnvironmentMetadata {
  /**
   * The development environment or platform used (e.g., 'Node.js v14.17.0').
   */
  environment: string;
  packageJson: {
    name: string;
    version: string;
    organization: string;
    description?: string;
    main?: string;
    type?: string;
    files?: string[];
    scripts?: {
      [k: string]: string;
    };
    repository?: {
      type: string;
      url: string;
      [k: string]: unknown;
    };
    license?: string;
    engines?: {
      [k: string]: string;
    };
    keywords?: string[];
    homepage?: string;
    dependencies?: {
      [k: string]: string;
    };
    devDependencies?: {
      [k: string]: string;
    };
    "lint-staged"?: {
      [k: string]: string;
    };
    _id?: string;
    [k: string]: unknown;
  };
  /**
   * The tool used for building or compiling the project (e.g., 'webpack v5.38.1').
   */
  buildTool?: string;
  /**
   * The Git commit hash corresponding to the codebase at the time of credential issuance.
   */
  commitHash?: string;
  /**
   * The date and time when the credential was generated.
   */
  timestamp: string;
  /**
   * A generic description of the operating system used in the development environment (e.g., 'Linux-based OS').
   */
  operatingSystem?: string;
  /**
   * The hashed hostname of the machine running the development environment.
   */
  hostname?: string;
  /**
   * The hashed IP address of the machine running the development environment.
   */
  ipAddress?: string;
  [k: string]: unknown;
}
