/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DIDAssertionCredential {
  /**
   * The unique identifier for the credential.
   */
  id: string;
  /**
   * The type of the credential, typically including 'VerifiableCredential'.
   */
  type: string[];
  /**
   * The entity that issued the credential.
   */
  issuer: {
    /**
     * The unique identifier for the issuer.
     */
    id: string;
    [k: string]: unknown;
  };
  credentialSubject: DIDAssertionCredentialSubject;
  /**
   * The context of the credential.
   */
  "@context": string[];
  /**
   * The expiration date of the credential.
   */
  expirationDate: string;
  [k: string]: unknown;
}
/**
 * The subject of the credential.
 */
export interface DIDAssertionCredentialSubject {
  /**
   * The DID that this credential is asserting information about.
   */
  id: string;
  /**
   * The type of assertion this credential makes about the DID.
   */
  assertionType: string;
  /**
   * Flexible metadata about the assertion, allowing any key-value pairs for extensibility.
   */
  assertionDetails?: {
    [k: string]: unknown;
  };
  verificationSteps?: {
    /**
     * The verification step performed.
     */
    step: string;
    result: "Passed" | "Failed";
    timestamp: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
