/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DIDAssertionCredential {
  /**
   * The unique identifier for the credential.
   */
  id: string;
  /**
   * The type of the credential, typically including 'VerifiableCredential'.
   */
  type: string[];
  /**
   * The entity that issued the credential.
   */
  issuer: string;
  /**
   * The date and time the credential was issued.
   */
  issuanceDate: string;
  credentialSubject: DIDAssertionCredentialSubject;
  /**
   * The proof used to verify the credential.
   */
  proof: {
    /**
     * The type of proof, e.g., 'Ed25519Signature2018'.
     */
    type: string;
    /**
     * The date and time the proof was created.
     */
    created: string;
    /**
     * The purpose of the proof, e.g., 'assertionMethod'.
     */
    proofPurpose: string;
    /**
     * The method used to verify the proof.
     */
    verificationMethod: string;
    /**
     * The JSON Web Signature of the proof.
     */
    jws: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * The subject of the credential.
 */
export interface DIDAssertionCredentialSubject {
  /**
   * The DID that this credential is asserting information about.
   */
  id: string;
  /**
   * The type of assertion this credential makes about the DID.
   */
  assertionType: string;
  /**
   * Flexible metadata about the assertion, allowing any key-value pairs for extensibility.
   */
  assertionDetails?: {
    [k: string]: unknown;
  };
  verificationSteps?: {
    /**
     * The verification step performed.
     */
    step: string;
    result: "Passed" | "Failed";
    timestamp: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
