/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DIDAssertionCredentialSubject {
  /**
   * The DID that this credential is asserting information about.
   */
  id: string;
  /**
   * The type of assertion this credential makes about the DID.
   */
  assertionType: string;
  /**
   * Flexible metadata about the assertion, allowing any key-value pairs for extensibility.
   */
  assertionDetails?: {
    [k: string]: unknown;
  };
  verificationSteps?: {
    /**
     * The verification step performed.
     */
    step: string;
    result: "Passed" | "Failed";
    timestamp: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
