/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DIDAssertionCredential {
  "@context": string[];
  /**
   * Unique identifier for this Verifiable Credential.
   */
  id?: string;
  type: string[];
  issuer: {
    /**
     * DID of the entity issuing the credential.
     */
    id: string;
    [k: string]: unknown;
  };
  /**
   * Timestamp when the credential was issued.
   */
  issuanceDate: string;
  /**
   * Optional expiration date for the credential.
   */
  expirationDate?: string;
  credentialSubject: {
    /**
     * The DID that this credential is asserting information about.
     */
    id: string;
    /**
     * The type of assertion this credential makes about the DID.
     */
    assertionType: string;
    /**
     * Flexible metadata about the assertion, allowing any key-value pairs for extensibility.
     */
    assertionDetails?: {
      [k: string]: unknown;
    };
    verificationSteps?: {
      /**
       * The verification step performed.
       */
      step: string;
      result: "Passed" | "Failed";
      timestamp: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  proof: {
    /**
     * Cryptographic proof type (e.g., Ed25519Signature2020).
     */
    type: string;
    /**
     * Timestamp when the proof was generated.
     */
    created: string;
    /**
     * Purpose of the proof.
     */
    proofPurpose: "assertionMethod";
    /**
     * DID URL of the key used to sign.
     */
    verificationMethod: string;
    /**
     * Cryptographic signature proving the assertion’s validity.
     */
    proofValue: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
