/**
 * Generated from RevenuDistribution.json
 * Schema: https://schemas.originvault.box/RevenueDistribution
 * DO NOT EDIT MANUALLY - regenerate with npm run generate-types
 */

/**
 * Defines how revenue from data sales is distributed to Data Chamber contributors.
 */
export interface RevenueDistribution {
  /**
   * DID of the Data Chamber.
   */
  chamberId: string;
  /**
   * Total revenue generated by data sales.
   */
  totalRevenue: number;
  /**
   * List of users and their payouts.
   */
  distribution: {
    /**
     * DID of the user receiving a payout.
     */
    recipientId?: string;
    /**
     * Payout amount.
     */
    amount?: number;
  }[];
  /**
   * When the revenue was distributed.
   */
  timestamp: string;
}
