name: Deploy to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'docs-site/**'
      - 'api/**'
      - 'schemas/**'
      - 'drafts/**'
      - 'contexts/**'
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd docs-site && npm ci
        
    - name: Build project
      run: |
        npm run build
        cd docs-site && npm run build
        
    - name: Deploy to Vercel (Preview)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./docs-site
        
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd docs-site && npm ci
        
    - name: Generate types and schemas
      run: |
        echo "🔄 Generating types and preparing schemas..."
        npm run generate-types
        
    - name: Build docs-site
      run: |
        echo "🏗️ Building docs-site for production..."
        cd docs-site
        npm run build
        
    - name: Deploy to Vercel (Production)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./docs-site
        
    - name: Verify deployment
      run: |
        echo "✅ Deployment completed"
        echo "🌐 Production URL: https://originvault-schema-registry.vercel.app"
        
    - name: Test API endpoints
      run: |
        echo "🧪 Testing deployed API endpoints..."
        sleep 30  # Wait for deployment to be ready
        
        # Test schema endpoints
        curl -f https://originvault-schema-registry.vercel.app/api/schemas || echo "⚠️ Schema API test failed"
        curl -f https://originvault-schema-registry.vercel.app/api/vc/schemas || echo "⚠️ VC Schema API test failed"
        
        echo "✅ API endpoint tests completed" 